services:
  angular-app:
    image: nginx:alpine
    container_name: portfolio
    ports:
      - "8080:80"
    volumes:
      - ./dist/Portfolio/browser:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
