runs-on: ubuntu-latest
strategy:
  matrix:
    node-version: [16.x]
steps:
  - uses: actions/checkout@v3
  - name: cache
    uses: actions/setup-node@v3
    with:
      node-version: ${{ matrix.node-version }}
      cache: 'npm'

  - name: install
    run: |
      npm ci
      npm install -g @angular/cli

  - name: build
    run: ng build --aot --optimization --progress=false

  - name: test
    run: ng test --browsers=ChromeHeadless --watch=false --code-coverage

  - name: lint
    run: ng lint
