# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  angular-full:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4
      - name: cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: install
        run: |
          npm install --global @angular/cli
          npm install

      - name: build
        run: ng build --aot --optimization --progress=false

      - name: test
        run: ng test --browsers=ChromeHeadless --watch=false --code-coverage

      - name: lint
        run: ng lint
